### ISSUE TITLE
Elucidated version

### ISSUE THREAD

**Issue by liangbingzhao** [lucidrains/video-diffusion-pytorch#15]
Is it possible to get a elucidated video diffusion model? or should I turn to your imagen repo? (see you have accomplish elucidate text2video in that repo)

**Comment by lucidrains** [comment]
@martinriven yes, i'm centralizing all text-to-video developments at [imagen-pytorch](https://github.com/lucidrains/imagen-pytorch#text-to-video-ongoing-research) . elucidated video diffusion should be immediately usable there
