### ISSUE TITLE
How to save a video？

### ISSUE THREAD

**Issue by 980202006** [lucidrains/video-diffusion-pytorch#2]
May I ask how many fps the output is, is there a code example for saving the video

**Comment by lucidrains** [comment]
yup, there will be - i plan on using `gifs` for starters - have a lot of code built out already in this repository https://github.com/lucidrains/nuwa-pytorch i'm a big noob when it comes to managing videos, so open to any suggestions

**Comment by 980202006** [comment]
Thank you!

**Comment by lucidrains** [comment]
@980202006 hello again! training should work for gifs now :) https://github.com/lucidrains/video-diffusion-pytorch/tree/0.0.14#training I'll be testing this on a moving mnist dataset (10 x 64 x 64) starting tonight (which I am also using to iron out issues with https://github.com/lucidrains/nuwa-pytorch, a completely attention-based approach to video synthesis)

**Comment by lucidrains** [comment]
it will also save samples of the tensors as gifs in the `./results` folder automatically every so often

you can always use this function https://github.com/lucidrains/video-diffusion-pytorch/blob/main/video_diffusion_pytorch/video_diffusion_pytorch.py#L647 manually too, for saving tensors of shape `(channels, frame, height, width)` to a gif file

**Comment by lucidrains** [comment]
training in progress! should have some generated gifs by tomorrow :) (hope it works 🤞)

**Comment by lucidrains** [comment]
![23](https://user-images.githubusercontent.com/108653/164500000-db3bcdf1-5c22-4ee5-9399-e0adccb3dfb6.gif)

hmm, nothing yet, i'll let it run for a week - but you should try it out! (for unconditional video training)

**Comment by 980202006** [comment]
Thank you! I will try it.

**Comment by oxjohanndiep** [comment]
how are your results after a week training?
