### ISSUE TITLE
attn mask suppose be `~mask`

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/video-diffusion-pytorch#6]
hi Phil,
might be a small typo? 
https://github.com/lucidrains/video-diffusion-pytorch/blob/aded599bedb62f7d6c595b3486b1be4a0053106c/video_diffusion_pytorch/video_diffusion_pytorch.py#L321

**Comment by lucidrains** [comment]
@CiaoHe you're definitely on the committee to reviewing my code when i get around to building AGI :laughing:

**Comment by lucidrains** [comment]
@CiaoHe thank you yet again!

**Comment by CiaoHe** [comment]
Wow. Hope to train an automatic debugger bot 🙈🙈🙈

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
